#!/usr/bin/env zsh

# Use this script to clean artifacts and temporary files generated by 'package-vscode.sh'.

set -e

cd ${0:a:h}
cd ..

for TOCLEAN in vscode-reh-darwin-arm64 VSCode-darwin-arm64 packaging/reh-linux packaging/out
do
    echo Cleaning $TOCLEAN
    rm -rf $TOCLEAN
done
